### PR TITLE
Easier build

### PR DESCRIPTION
**Pull request by samoht**

### CODE REVIEW

**Comment by samoht** [comment]
Greeeeen!

**Comment by yomimono** [comment]
> Sorry, we could not display the entire diff because too many files (460) changed.

I like the part where it builds, though!

**Comment by samoht** [comment]
Almost there but https://ci.appveyor.com/project/docker/vpnkit/build/1.0.86/artifacts does not show `com.docker.slirp.exe`

**Comment by samoht** [comment]
The CIs are happy, the build artifacts are uploaded. Merging!

**Pull request merged**
