### PR TITLE
Add a 9P debug interface

### PR DESCRIPTION
**Pull request by djs55**
This PR allows a 9P filesystem to be exposed (over Unix domain socket or Windows named pipe) which allows the active network connections to be listed. For example:

```
 ~/mirage/ocaml-9p/_build/src/main.native ls connections --address unix:/tmp/slirp.socket
drwxrwxr-x ? root root 0 Jan 1 1970 unix:/Users/djs/Library/Containers/com.docker.docker/Data/s50
drwxrwxr-x ? root root 0 Jan 1 1970 unix:/tmp/slirp.socket
drwxrwxr-x ? root root 0 Jan 1 1970 tcp:52.85.67.201:443
drwxrwxr-x ? root root 0 Jan 1 1970 unix:/Users/djs/Library/Containers/com.docker.docker/Data/s51
drwxrwxr-x ? root root 0 Jan 1 1970 unix:/Users/djs/Library/Containers/com.docker.docker/Data/s40
drwxrwxr-x ? root root 0 Jan 1 1970 unix:/Users/djs/Library/Containers/com.docker.docker/Data/s50
drwxrwxr-x ? root root 0 Jan 1 1970 unix:/Users/djs/Library/Containers/com.docker.docker/Data/s51
drwxrwxr-x ? root root 0 Jan 1 1970 udp:192.168.65.2:41712-127.0.0.1:123
drwxrwxr-x ? root root 0 Jan 1 1970 unix:/tmp/slirp.socket
```

This uses the handy VFS library included with http://github.com/docker/datakit

Future patches could allow the connections to be manipulated e.g. `rm` to close.

This PR removes the SIGUSR1 interface which was tricky to use because it was a bit asynchronous.

### CODE REVIEW

**Comment by samoht** [comment]
You will probably need a release of datakit to make that work, I can make one later today.

**Comment by djs55** [comment]
Unfortunately the ocamlgraph download server seems broken too:
```
$ wget http://ocamlgraph.lri.fr/download/ocamlgraph-1.8.7.tar.gz
--2016-09-29 11:43:40--  http://ocamlgraph.lri.fr/download/ocamlgraph-1.8.7.tar.gz
Resolving ocamlgraph.lri.fr... 129.175.15.11
Connecting to ocamlgraph.lri.fr|129.175.15.11|:80... connected.
HTTP request sent, awaiting response...
```

**Comment by djs55** [comment]
Appveyor build recorded "Cancelled 4 hours ago in 52 min 23 sec" -- perhaps there's just too much code being built here?

**Comment by djs55** [comment]
I've switched the dependency to `datakit-client` following the https://github.com/mirage/mirage-dev/pull/149 example. Hopefully this builds in time.

**Comment by djs55** [comment]
As expected, `Fs9p` is missing:
```
File "src/main.ml", line 100, characters 22-31:
Error: Unbound module Fs9p
Command exited with code 2.
```

**Comment by djs55** [comment]
Woo, build finally successful!

**Comment by samoht** [comment]
@djs55 I am releasing `datakit-server` today and I'll rebase your PR to use it directly.

**Pull request merged**
