### PR TITLE
Add a COMMIT file to the artifacts

### PR DESCRIPTION
**Pull request by samoht**

### CODE REVIEW

**Comment by yomimono** [comment]
Looks good to me, as long as CI agrees.

**Comment by samoht** [comment]
Just don't merge it yet, I need to verify something first.

**Comment by samoht** [comment]
Hum the CI on Windows is completely broken but still is green. I'm trying to fix that now ...

**Comment by samoht** [comment]
```
#=== ERROR while installing ofs.local =========================================#
# opam-version 1.2.2
# os           darwin
# command      ./configure --prefix /Users/distiller/vpnkit/_build/opam/4.02.3
# path         /Users/distiller/vpnkit/_build/opam/4.02.3/build/ofs.local
# compiler     4.02.3
# exit-code    1
# env-file     /Users/distiller/vpnkit/_build/opam/4.02.3/build/ofs.local/ofs-10031-817288.env
# stdout-file  /Users/distiller/vpnkit/_build/opam/4.02.3/build/ofs.local/ofs-10031-817288.out
# stderr-file  /Users/distiller/vpnkit/_build/opam/4.02.3/build/ofs.local/ofs-10031-817288.err
### stderr ###
# ocamlfind: Package `cstruct.syntax' not found
# W: Field 'pkg_cstruct_syntax' is not set: Command ''/Users/distiller/vpnkit/_build/opam/4.02.3/bin/ocamlfind' query -format %d cstruct.syntax > '/var/folders/jm/fw86rxds0xn69sk40d18y69m0000gp/T/oasis-8dd613.txt'' terminated with error code 2
# E: Cannot find findlib package cstruct.syntax
# E: Failure("1 configuration error")


#=== ERROR while installing tcpip.999 =========================================#
# opam-version 1.2.2
# os           darwin
# command      ./configure --prefix /Users/distiller/vpnkit/_build/opam/4.02.3 --disable-xen --disable-unix
# path         /Users/distiller/vpnkit/_build/opam/4.02.3/build/tcpip.999
# compiler     4.02.3
# exit-code    1
# env-file     /Users/distiller/vpnkit/_build/opam/4.02.3/build/tcpip.999/tcpip-10031-ec53e1.env
# stdout-file  /Users/distiller/vpnkit/_build/opam/4.02.3/build/tcpip.999/tcpip-10031-ec53e1.out
# stderr-file  /Users/distiller/vpnkit/_build/opam/4.02.3/build/tcpip.999/tcpip-10031-ec53e1.err
### stderr ###
# ocamlfind: Package `cstruct.syntax' not found
# W: Field 'pkg_cstruct_syntax' is not set: Command ''/Users/distiller/vpnkit/_build/opam/4.02.3/bin/ocamlfind' query -format %d cstruct.syntax > '/var/folders/jm/fw86rxds0xn69sk40d18y69m0000gp/T/oasis-e1ccde.txt'' terminated with error code 2
# E: Cannot find findlib package cstruct.syntax
# E: Failure("1 configuration error")
```

:-(

**Comment by samoht** [comment]
ok, I've removed the artificial dependency of ofs to `camp4`, add a missing dependency in `proto-vmnet` and I've added a constraint to force tcpip.999 to use an older version of cstruct. Hopefully this should fix the build issues ...

**Comment by samoht** [comment]
@yomimono If you improve tcpip.999 to not use camlp4, don't forget to drop the constraint that I have added :-)

**Comment by yomimono** [comment]
I'm cherry-picking stuff for tcpip.999 atm

**Pull request merged**
