### PR TITLE
Add port forwarding unit tests

### PR DESCRIPTION
**Pull request by djs55**
- check that we can connect, send and receive data forwarded to a local service
- measure the time taken to perform 10 sequential connections

In particular the timing test will only fail of the connection is outrageously slow: on my MBP 10 connections takes about 0.003s. It will only take more than 1s if there's a > 100ms delay on the average connection.

### CODE REVIEW

**Comment by djs55** [comment]
I don't want to merge this until after #57 is merged and the tests re-run to verify they pass on both OSX and Windows. In particular the timing test might fail on Windows (!)

**Comment by samoht** [comment]
#57 is merged, can you rebase this PR?

**Comment by djs55** [comment]
@samoht @yomimono rebased and CI has passed-- happy to merge?

**Comment by yomimono** [comment]
@djs55 looks good to me!

**Comment by djs55** [comment]
Thanks!

**Pull request merged**
