### PR TITLE
don't add DHCP options with empty lists

### PR DESCRIPTION
**Pull request by yomimono**
See https://github.com/mirage/charrua-core/pull/48 for more discussion.

### CODE REVIEW

**Comment by yomimono** [comment]
@MagnusS @djs55 - I have no idea where to begin with the failing CircleCI test (`bash: line 1: brew: command not found`); any hints?

**Comment by djs55** [comment]
I found a similar report https://discuss.circleci.com/t/brew-not-installed-on-some-containers/7483/4 which suggests that it's a broken CircleCI "container". It sounds like it needs to be reported to CircleCI somehow :/

I think the patch looks good -- perhaps if someone could confirm that it really does build locally and the tests still work we could ignore the CI failure and merge anyway.

**Comment by yomimono** [comment]
@djs55 how do you normally build this locally?  `docker build .` fails with a disagreement between `tcpip` and another package on whether `lib/ethif.ml` requires `mtu`.  I remember discussing this with @dave-tucker but not the outcome :(

**Comment by MagnusS** [comment]
@yomimono there may be better ways, but I usually build in a separate opam root with ./repo/darwin as the only repo. Something like this:
```
opam init --root=~/vpnkit_root ./repo/darwin
eval ($opam config env --root=~/vpnkit_root)
opam install --deps-only slirp
make
```

I updated the instructions in the README a few weeks ago, but they are a bit outdated now - I don't think it works to just add the vpnkit repo if you already have the main opam repo set up (at least it didnt the last time I tried)

**Comment by yomimono** [comment]
Thanks @MagnusS!  Here's the result of `make test`:

```
[4.03.0] (no-empty-domain-search) computer:vpnkit user$ make
jbuilder build src/bin/main.exe
Workspace root: /Users/user/vpnkit
Running[0]: /Users/user/vpnkit_root/4.03.0/bin/ocamlfind printconf path > /var/folders/hw/w70thd3d7m53x75gs0zgssm00000gn/T/jbuild664847.output
Running[1]: /Users/user/vpnkit_root/4.03.0/bin/ocamlc.opt -config > /var/folders/hw/w70thd3d7m53x75gs0zgssm00000gn/T/jbuilda7fdf2.output
Actual targets:
- _build/default/src/bin/main.exe
cp _build/default/src/bin/main.exe vpnkit.exe
[4.03.0] (no-empty-domain-search) elaine-marley:vpnkit user$ make test
jbuilder build src/hostnet_test/main_lwt.exe
Workspace root: /Users/user/vpnkit
Running[0]: /Users/user/vpnkit_root/4.03.0/bin/ocamlfind printconf path > /var/folders/hw/w70thd3d7m53x75gs0zgssm00000gn/T/jbuild4e919d.output
Running[1]: /Users/user/vpnkit_root/4.03.0/bin/ocamlc.opt -config > /var/folders/hw/w70thd3d7m53x75gs0zgssm00000gn/T/jbuild121200.output
Actual targets:
- _build/default/src/hostnet_test/main_lwt.exe
jbuilder build src/hostnet_test/main_uwt.exe
Workspace root: /Users/user/vpnkit
Running[0]: /Users/user/vpnkit_root/4.03.0/bin/ocamlfind printconf path > /var/folders/hw/w70thd3d7m53x75gs0zgssm00000gn/T/jbuildd9e4bd.output
Running[1]: /Users/user/vpnkit_root/4.03.0/bin/ocamlc.opt -config > /var/folders/hw/w70thd3d7m53x75gs0zgssm00000gn/T/jbuildbc1b9d.output
Actual targets:
- _build/default/src/hostnet_test/main_uwt.exe
./_build/default/src/hostnet_test/main_lwt.exe
Testing Hostnet.
[OK]                hosts_with_Lwt               0   hosts Windows-style.
[OK]                hosts_with_Lwt               1   hosts Mac-style.
[OK]                Forwarding_with_Lwt          0   Test one port forward.
[OK]                Forwarding_with_Lwt          1   Check speed of 10 forwarded connections.
[OK]                DHCP_with_Lwt                0   Simple query.
[OK]                DNS UDP_with_Lwt             0   Use 8.8.8.8 to lookup www.google.com.
[OK]                DNS UDP_with_Lwt             1   Service a query from /etc/hosts cache.
[OK]                DNS UDP_with_Lwt             2   Use 8.8.8.8 to lookup www.google.com via 192.168.65.3.
[OK]                DNS UDP_with_Lwt             3   Use 8.8.8.8 to lookup www.google.com via 192.168.65.4.
[OK]                DNS UDP_with_Lwt             4   Use 8.8.8.8 to lookup www.google.com via 192.168.65.5.
[OK]                DNS UDP_with_Lwt             5   Use 8.8.8.8 to lookup www.google.com via 192.168.65.6.
[OK]                DNS UDP_with_Lwt             6   Use 8.8.8.8 to lookup www.google.com via 192.168.65.7.
[OK]                DNS UDP_with_Lwt             7   Use 8.8.8.8 to lookup www.google.com via 192.168.65.8.
[OK]                DNS UDP_with_Lwt             8   Use 8.8.8.8 to lookup www.google.com via 192.168.65.9.
[OK]                DNS UDP_with_Lwt             9   Use 8.8.8.8 to lookup www.google.com via 192.168.65.10.
[OK]                TCP_with_Lwt                 0   HTTP GET http://www.google.com/.
[OK]                TCP_with_Lwt                 1   HTTP GET fails beyond max connections.
[OK]                TCP_with_Lwt                 2   1 TCP connection transferring 1 KiB.
[OK]                UDP_with_Lwt                 0   Shared NAT rule.
[OK]                UDP_with_Lwt                 1   1 UDP connection.
[OK]                UDP_with_Lwt                 2   2 UDP connections.
[OK]                UDP_with_Lwt                 3   NAT punch.
[OK]                UDP_with_Lwt                 4   Source ports.
[OK]                hosts                        0   hosts Windows-style.
[OK]                hosts                        1   hosts Mac-style.
The full test results are available in `_build/_tests`.
Test Successful in 0.077s. 25 tests run.
./_build/default/src/hostnet_test/main_uwt.exe
Testing Hostnet.
[OK]                hosts_with_Uwt               0   hosts Windows-style.
[OK]                hosts_with_Uwt               1   hosts Mac-style.
[OK]                Forwarding_with_Uwt          0   Test one port forward.
[OK]                Forwarding_with_Uwt          1   Check speed of 10 forwarded connections.
[OK]                DHCP_with_Uwt                0   Simple query.
[OK]                DNS UDP_with_Uwt             0   Use 8.8.8.8 to lookup www.google.com.
[OK]                DNS UDP_with_Uwt             1   Service a query from /etc/hosts cache.
[OK]                DNS UDP_with_Uwt             2   Use 8.8.8.8 to lookup www.google.com via 192.168.65.3.
[OK]                DNS UDP_with_Uwt             3   Use 8.8.8.8 to lookup www.google.com via 192.168.65.4.
[OK]                DNS UDP_with_Uwt             4   Use 8.8.8.8 to lookup www.google.com via 192.168.65.5.
[OK]                DNS UDP_with_Uwt             5   Use 8.8.8.8 to lookup www.google.com via 192.168.65.6.
[OK]                DNS UDP_with_Uwt             6   Use 8.8.8.8 to lookup www.google.com via 192.168.65.7.
[OK]                DNS UDP_with_Uwt             7   Use 8.8.8.8 to lookup www.google.com via 192.168.65.8.
[OK]                DNS UDP_with_Uwt             8   Use 8.8.8.8 to lookup www.google.com via 192.168.65.9.
[OK]                DNS UDP_with_Uwt             9   Use 8.8.8.8 to lookup www.google.com via 192.168.65.10.
[OK]                TCP_with_Uwt                 0   HTTP GET http://www.google.com/.
[OK]                TCP_with_Uwt                 1   HTTP GET fails beyond max connections.
[OK]                TCP_with_Uwt                 2   1 TCP connection transferring 1 KiB.
[OK]                UDP_with_Uwt                 0   Shared NAT rule.
[OK]                UDP_with_Uwt                 1   1 UDP connection.
[OK]                UDP_with_Uwt                 2   2 UDP connections.
[OK]                UDP_with_Uwt                 3   NAT punch.
[OK]                UDP_with_Uwt                 4   Source ports.
[OK]                hosts                        0   hosts Windows-style.
[OK]                hosts                        1   hosts Mac-style.
The full test results are available in `_build/_tests`.
Test Successful in 0.055s. 25 tests run.

```

**Comment by djs55** [comment]
I see appveyor is happy too, so I think we can ignore the CircleCI failure.

**Pull request merged**
